name: royale-tools
channels:
  - conda-forge
dependencies:
  # Main packages
  - python=3.7
  - pysimplegui=4.29.0
  - requests=2.24.0
  # Dev packages
  - loguru=0.5.0
  - mypy=0.782
  - black=20.8b1
  - isort=5.5.3
  - pre-commit=2.7.1
  - flake8=3.8.3
  - flake8-docstrings=1.5.0